provider:
  name: openfaas
  gateway: http://localhost:8080  # can be a remote server

functions:
  nslookup:
    lang: Dockerfile
    handler: ./nslookup
    image: bibarrav/openfaas-nslookup:latest
